version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ads
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/ads
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: {}
