### Создаем объявление
POST http://127.0.0.1:5000/ads
Content-Type: application/json

{
  "title": "Продается самокат",
  "description": "Годный, можно крутить вертухи",
  "owner": "Доминик Торетто"
}

### Получаем объявление
GET http://127.0.0.1:5000/ads/1

### Удаляем объявление
DELETE http://127.0.0.1:5000/ads/1
